services:
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PWD=postgres
      - DB_DB=postgres
      - DB_HOST=db
      - DB_PORT=5432
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
      - 3000:3000
    environment:
      - VITE_API_URL= http://0.0.0.0:8000/

    depends_on:
      - backend

volumes:
  pgdata: {}