version: '3.9'

services:
  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
  backend:
    build: ./backend
    command: python manage.py runserver 
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
   postgres_data: